# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 11:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blist_ui', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucketlist',
            name='description',
            field=models.TextField(blank=True, verbose_name=b''),
        ),
        migrations.AlterField(
            model_name='bucketlist',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name=b''),
        ),
        migrations.AlterField(
            model_name='bucketlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bucketlistitem',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name=b'List Item Name'),
        ),
        migrations.AlterField(
            model_name='bucketlistitem',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='blist_ui.Status'),
        ),
        migrations.AlterField(
            model_name='status',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='State_inserted_by', to=settings.AUTH_USER_MODEL, verbose_name=b'Inserted By'),
        ),
    ]
